Performance Transform Dimensions & Concurrency
BunkerDB/linkedin-tl pull request #4
Opened 2022-01-11 19:17 UTC by facuigua

- Created new topic/MongoDB collection Dimensions & Populate through Debezium/Kafka Event
- Custom concurrency calculation

PR Asociado:
https://github.com/BunkerDB/linkedin-e/pull/5

2022-01-12 15:23 UTC, fedegara approved these changes

2022-01-14 00:50 UTC, carlos-ratia requested changes

2022-01-14 00:50 UTC, carlos-ratia commented on src/Infrastructure/DBAL/DAO/DimensionsMongoAdapter.ts
> +  findByIdAndType(_: { id: string; type: Dimension }): PromiseB<DimensionsDTO> {
Hola @facuigua revisando este metodo no se utiliza en ningun lado en la logica de negocio; revisalo si no lo removemos de la interface IDimensionsDAO y luego de sus implementaciones

2022-01-14 18:29 UTC, facuigua commented on src/Infrastructure/DBAL/DAO/DimensionsMongoAdapter.ts
> +        throw new Error("<Dimensions> not found");
Corregido

2022-01-14 18:30 UTC, facuigua commented on src/Infrastructure/DBAL/DAO/DimensionsMongoAdapter.ts
> +  findByIdAndType(_: { id: string; type: Dimension }): PromiseB<DimensionsDTO> {
Carlos, tienes razon, cree la definicion por si en algun momento se llegue a necesitar, pero teniendo en cuenta que por lo poronto no es necesario, se puede remover.

2022-01-17 13:42 UTC, carlos-ratia approved these changes

2022-01-17 13:44 UTC, merged