fix BUN-13657
BunkerDB/linkedin-tl pull request #8
Opened 2022-06-03 17:09 UTC by emimarz

ticket https://bunker.atlassian.net/browse/BUN-13765

2022-06-03 21:08 UTC, carlos-ratia requested changes

2022-06-03 21:08 UTC, carlos-ratia commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +        moment().utc(false).subtract(1, "day").format()
@emimarz verificar el formato

2022-06-03 21:08 UTC, carlos-ratia commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +      const currentDate: Date = new Date(
@emimarz en la DB como se guarda data en YYYY-MM-DD || Y-m-d H:i:s

2022-06-03 21:08 UTC, carlos-ratia commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +                console.error(err.message);
@emimarz  verficar no existe un logger implementado

2022-06-08 14:25 UTC, emimarz commented on package-lock.json
> +  "packages": {
@carlos-ratia  pense que habia sido por la actualizacion de node

2022-06-08 14:27 UTC, emimarz commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +        moment().utc(false).subtract(1, "day").format()
el .format() genera el formato por defecto y revise lo que responde y esta todo ok

2022-06-08 14:27 UTC, emimarz commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +    if (rawRow.total != undefined) {
cambiando...

2022-06-08 14:31 UTC, emimarz commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +                console.error(err.message);
bueno

2022-06-09 17:59 UTC, asgallettoh commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +            todayData.metrics.followers != undefined &&
el operador seria !== no?

2022-06-09 17:59 UTC, asgallettoh commented on src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
> +            todayData.metrics.followers != undefined &&
el operador seria !== no?

2022-06-09 18:00 UTC, asgallettoh approved these changes

2022-06-09 20:27 UTC, asgallettoh approved these changes

2022-06-09 20:43 UTC, carlos-ratia requested changes

2022-06-09 20:43 UTC, carlos-ratia commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          return this.collection.updateOne(query, update, options);
@emimarz falto manejo de posible errores

2022-06-09 20:43 UTC, carlos-ratia commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          if (itemData.metrics.followers) {
@emimarz esta comparacion a que se refiere?

2022-06-09 20:43 UTC, carlos-ratia requested changes

2022-06-09 20:43 UTC, carlos-ratia commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +            if (followersData) {
@emimarz esta comparacion a que se refiere?

2022-06-09 21:00 UTC, asgallettoh approved these changes

2022-06-10 02:21 UTC, emimarz commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          if (itemData.metrics.followers) {
se refiere a: que dentro de metrics exista la propiedad followers, hay casos donde no existe dicha propiedad

2022-06-10 02:32 UTC, emimarz commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +            if (followersData) {
en su momento tenia sentido pero ahora estoy viendo un if anterior 
`      if (followersData !== undefined && dimensionDate !== yesterday) 
`
que lo chequea, asi que lo saco

2022-06-10 02:36 UTC, emimarz commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          return this.collection.updateOne(query, update, options);
lo controlo despues, puse un nivel mas arriba en el archivo
src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts
linea 74
un catch, esta mal?

2022-06-10 13:10 UTC, asgallettoh commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          return this.collection.updateOne(query, update, options);
Si peor capaz ta bueno levantar el error en donde ocurre y dejarle un msj mas claro por si el error que tira no se entiende del todo cuando explota por default.

2022-06-10 14:09 UTC, emimarz commented on src/Infrastructure/DBAL/DAO/DataGraphFollowersStatisticsMongoAdapter.ts
> +          return this.collection.updateOne(query, update, options);
hablado con carlos en call

2022-06-10 14:12 UTC, emimarz commented on package-lock.json
> +  "packages": {
hablado en call se hace rollback

2022-06-10 14:22 UTC, carlos-ratia approved these changes

2022-06-10 14:28 UTC, merged

2022-06-10 14:49 UTC, facuigua reviewed
Todo Ok